apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: ap-southeast-2
  version: "1.20"

availabilityZones: ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 1
  instanceType: t3.small
  ssh:
    enableSsm: true
